name: clear

on:
  # schedule:
  #   - cron: '30 22 * * 3' # UTC时间的10:30，对应中国时间6:30
  # push:
  workflow_dispatch:
  # pull_request:
  # branches: [main, dev]
env:
  TZ: Asia/Shanghai

jobs:
  clear:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'dev')
    name: clear
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: Apocalypsor/Workflows-Cleaner

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-cache-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-pip-
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/requirements
          key: ${{ runner.os }}-cache-requirements-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-cache-requirements
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: |
          pipenv install --deploy --ignore-pipfile
      - name: Install dependencies
        run: |
          pipenv requirements > requirements.txt
          pip install -r requirements.txt
      - name: Run Python script
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
          EXPIRE_TIME: 12h
        run: python run.py
